Added base classes to implement offline mechanisms
Wolox/wolmo-networking-android pull request #1
Opened 2017-05-03 17:28 UTC by juanignaciomolina

# Added base classes to implement offline mechanisms

Added the following classes required to implement a basic offline mechanism and API requests collapsing.

* BaseCallCollapser
* ICallCollapser
* ICache
* IRepositoryCallback
* IUpdate
* Repository

2017-05-24 15:10 UTC, SpicyCactuar requested changes
Some minor changes. Looking gooooood!

2017-05-24 15:10 UTC, emalamela commented on networking/build.gradle
> +        targetSdkVersion 25
Libraries don't have `versionCode` and/or `versionName`?

2017-05-24 15:10 UTC, emalamela commented on networking/src/main/AndroidManifest.xml
> +        android:theme="@style/AppTheme">
Just a minor thing, we can self-enclose this xml by using `/>`.

2017-05-24 15:10 UTC, emalamela commented on networking/src/main/res/values/colors.xml
> +<?xml version="1.0" encoding="utf-8"?>
Is this file needed?

2017-05-24 15:10 UTC, emalamela commented on networking/src/main/res/values/styles.xml
> +<resources>
Same as the other empty file :wink:.

2017-05-30 17:57 UTC, juanignaciomolina commented on networking/build.gradle
> +        targetSdkVersion 25
Nope, that's for regular apps. 
Both `versionCode` and `versionName` are used for app's updates (not library updates, that is specified in the version of the libraries used in the gradle config file for each app).

2017-05-30 17:57 UTC, juanignaciomolina commented on networking/src/main/AndroidManifest.xml
> +        android:theme="@style/AppTheme">
Sure, np.

2017-05-30 17:57 UTC, juanignaciomolina commented on networking/src/main/res/values/colors.xml
> +<?xml version="1.0" encoding="utf-8"?>
File removed!

2017-05-30 17:57 UTC, juanignaciomolina commented on networking/src/main/res/values/styles.xml
> +<resources>
File removed!

2017-05-30 18:10 UTC, juanignaciomolina commented
@emalamela Added the requested changes in https://github.com/Wolox/wolmo-networking-android/pull/2

Since we have to include the changes in that PR as well, please review that PR (which is pointing to the branch of this PR) and once that it is ready to go, we merge that one into this one. After that, we can merge to master and we are done with the networking module. Do you agree? :)

2017-05-31 16:34 UTC, SpicyCactuar approved these changes
*Ripple effect!*

2017-05-31 16:38 UTC, merged